SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, 
JOB_NAME, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
JOIN JOB USING(JOB_CODE);


SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, 
JOB_NAME, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
JOIN JOB USING(JOB_CODE)
WHERE EMP_NO = '770808-2665412';

SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, 
JOB_NAME, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
JOIN JOB USING(JOB_CODE)
WHERE DEPT_TITLE = '총무부';

SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, 
JOB_NAME, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
JOIN JOB USING(JOB_CODE)
WHERE SALARY >= 3000000;

SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, 
JOB_NAME, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
JOIN JOB USING(JOB_CODE)
WHERE EMP_ID = 200;

SELECT NVL(DEPT_CODE, '부서없음') DEPT_CODE, SUM(SALARY) SALARY
FROM EMPLOYEE
GROUP BY DEPT_CODE;

SELECT JOB_NAME, ROUND(AVG(SALARY), 1) SALARY
FROM EMPLOYEE
LEFT JOIN JOB USING(JOB_CODE)
GROUP BY JOB_NAME, JOB_CODE
ORDER BY JOB_CODE;

CREATE TABLE TB_TEST(
	TEST_NO NUMBER PRIMARY KEY,
	TEST_TITLE VARCHAR2(100) NOT NULL,
	TEST_CONTENT VARCHAR2(500) NOT NULL
);