-- 로그인 SQL

SELECT MEMBER_NO, MEMBER_ID, MEMBER_NM, MEMBER_GENDER, 
TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') ENROLL_DATE
FROM MEMBER
WHERE MEMBER_ID = ? 
AND MEMBER_PW = ? 
AND SECESSION_FL = 'N';


-- 아이디 중복검사

SELECT COUNT(*) FROM MEMBER
WHERE MEMBER_ID = 'user01'
AND SECESSION_FL = 'N';

-- 회원가입

INSERT INTO MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, ?, ?, ?, ?, DEFAULT, DEFAULT);

-- 정보변경

UPDATE MEMBER SET MEMBER_NM = '김일tnd' WHERE MEMBER_ID = 'user01';

INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user06', 'pass06', '황인범', 'M', DEFAULT, DEFAULT);

SELECT * FROM MEMBER;

DELETE FROM MEMBER
WHERE MEMBER_ID = 'user04';

GRANT RESOURCE, CONNECT TO member_ms;